let dataImages = {
    Caroussel1:require("../assets/imgs/carousel1.jpg"),
Caroussel2:require("../assets/imgs/carousel2.jpg"),
Caroussel3:require("../assets/imgs/carousel3.webp"),
shopy1:require("../assets/imgs/item-03.jpg"),
shopy2:require("../assets/imgs/shopi2.webp"),
shopy3:require("../assets/imgs/shopy3.webp"),
shopy4:require("../assets/imgs/shopy4.webp"),
shopy5:require("../assets/imgs/shopy5.webp"),
shopy6:require("../assets/imgs/shopy6.webp"),
shopy7:require("../assets/imgs/shopy7.webp"),
shopy8:require("../assets/imgs/shopy8.webp"),
card1:require("../assets/imgs/cards1.webp"),
card2:require("../assets/imgs/cards2.webp"),
card3:require("../assets/imgs/cards3.webp"),
card4:require("../assets/imgs/cards4.webp"),
card5:require("../assets/imgs/cards5.webp"),
card6:require("../assets/imgs/cards6.webp"),
banner:require("../assets/imgs/banner-08.jpg"),
blog1:require("../assets/imgs/blog-01.jpg"),
blog2:require("../assets/imgs/blog-02.jpg"),
blog3:require("../assets/imgs/blog-03.jpg"),
banner:require("../assets/imgs/banner.webp")
}
export default  dataImages